version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/azure/tests/site-files:/usr/share/nginx/html
      - /home/azure/tests/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/azure/tests/nginx/ssl-params.conf:/etc/ssl/ssl-params.conf
      - /home/azure/tests/nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - /home/azure/tests/letsencrypt/etc:/etc/letsencrypt